### ISSUE TITLE
side knob

### ISSUE THREAD

**Issue by cannap** [Rocco-Gossmann/GoWas#1]
it does not recognize my mouse side knobs  or the left and right click 

![image](https://github.com/Rocco-Gossmann/GoWas/assets/1394151/ec7c12cf-2900-44bf-9484-c4f813a39dff)

**Comment by cannap** [comment]
the mouse is just blinking

https://github.com/Rocco-Gossmann/GoWas/assets/1394151/675c9bfe-4c8c-4181-803d-f48fa200ed05

**Comment by Rocco-Gossmann** [comment]
Hey, thanks for the Report. It helped uncover another Issue with the Mouse-Buttons

The Buttons were actually picked up but there were no graphics to representing them. (Hence the Icon flickering).

I've updated the demo page.
The icon only reacts to the first 3 buttons it shows.
But there is also a little text now, that shows what buttons were picked up.
